version: 2
#2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        freshness: 
          warn_after:
            count: 1
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        identifier: raw_gz_sales
        description: sales of greenweez
        tests:
          - unique:
              column_name: "(orders_id||'-'||pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase

      - name: ship
        identifier: raw_gz_ship
        description: ship data of greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: product
        identifier: raw_gz_product
        description: product data of greeweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
            
      - name: adwords
        identifier: raw_gz_adwords
        description: data of adwords
        columns:
          - name: campaign_key
        
      - name: bing
        identifier: raw_gz_bing
        description: data of bing
      
      - name: criteo
        identifier: raw_gz_criteo
        description: data of criteo
      
      - name: facebook
        identifier: raw_gz_facebook
        description: data of facebook

      - name: campaigns
        identifier: int_campaigns

      - name: campaigns_daily
        identifier: int_campaigns_day


      - name: finance_campaigns_daily
        identifier: finance_campaigns_day
